In [208]:
paragraph =  """I have three visions for India. In 3000 years of our history, people from all over 
               the world have come and invaded us, captured our lands, conquered our minds. 
               From Alexander onwards, the Greeks, the Turks, the Moguls, the Portuguese, the British,
               the French, the Dutch, all of them came and looted us, took over what was ours. 
               Yet we have not done this to any other nation. We have not conquered anyone. 
               We have not grabbed their land, their culture, 
               their history and tried to enforce our way of life on them. 
               Why? Because we respect the freedom of others.That is why my 
               first vision is that of freedom. I believe that India got its first vision of 
               this in 1857, when we started the War of Independence. It is this freedom that
               we must protect and nurture and build on. If we are not free, no one will respect us.
               My second vision for India’s development. For fifty years we have been a developing nation.
               It is time we see ourselves as a developed nation. We are among the top 5 nations of the world
               in terms of GDP. We have a 10 percent growth rate in most areas. Our poverty levels are falling.
               Our achievements are being globally recognised today. Yet we lack the self-confidence to
               see ourselves as a developed nation, self-reliant and self-assured. Isn’t this incorrect?
               I have a third vision. India must stand up to the world. Because I believe that unless India 
               stands up to the world, no one will respect us. Only strength respects strength. We must be 
               strong not only as a military power but also as an economic power. Both must go hand-in-hand. 
               My good fortune was to have worked with three great minds. Dr. Vikram Sarabhai of the Dept. of 
               space, Professor Satish Dhawan, who succeeded him and Dr. Brahm Prakash, father of nuclear material.
               I was lucky to have worked with all three of them closely and consider this the great opportunity of my life. 
               I see four milestones in my career"""

In [209]:
from nltk.stem.porter import PorterStemmer 
stem = PorterStemmer()

In [210]:
from nltk.stem.wordnet import WordNetLemmatizer 
lem = WordNetLemmatizer()

In [211]:
import nltk

In [212]:
import nltk
import re
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer
from nltk.stem import WordNetLemmatizer
sentences= nltk.sent_tokenize(paragraph)

In [213]:

sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [stem.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [214]:
corpus

['three vision india',
 'year histori peopl world come invad us captur land conquer mind',
 'alexand onward greek turk mogul portugues british french dutch came loot us took',
 'yet done nation',
 'conquer anyon',
 'grab land cultur histori tri enforc way life',
 '',
 'respect freedom other first vision freedom',
 'believ india got first vision start war independ',
 'freedom must protect nurtur build',
 'free one respect us',
 'second vision india develop',
 'fifti year develop nation',
 'time see develop nation',
 'among top nation world term gdp',
 'percent growth rate area',
 'poverti level fall',
 'achiev global recognis today',
 'yet lack self confid see develop nation self reliant self assur',
 'incorrect',
 'third vision',
 'india must stand world',
 'believ unless india stand world one respect us',
 'strength respect strength',
 'must strong militari power also econom power',
 'must go hand hand',
 'good fortun work three great mind',
 'dr vikram sarabhai dept',
 'space profess

In [215]:
ps = PorterStemmer()
wordnet=WordNetLemmatizer()
sentences = nltk.sent_tokenize(paragraph)
corpus = []
for i in range(len(sentences)):
    review = re.sub('[^a-zA-Z]', ' ', sentences[i])
    review = review.lower()
    review = review.split()
    review = [lem.lemmatize(word,'v') for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)

In [216]:
corpus

['three visions india',
 'years history people world come invade us capture land conquer mind',
 'alexander onwards greeks turks moguls portuguese british french dutch come loot us take',
 'yet do nation',
 'conquer anyone',
 'grab land culture history try enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india get first vision start war independence',
 'freedom must protect nurture build',
 'free one respect us',
 'second vision india development',
 'fifty years develop nation',
 'time see develop nation',
 'among top nations world term gdp',
 'percent growth rate areas',
 'poverty level fall',
 'achievements globally recognise today',
 'yet lack self confidence see develop nation self reliant self assure',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect us',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune work three great mind'

In [117]:
# Creating the TF-IDF model
from sklearn.feature_extraction.text import TfidfVectorizer
cv = TfidfVectorizer()
X = cv.fit_transform(corpus).toarray()

In [118]:
X

array([[0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.31833851,
        0.        ],
       [0.        , 0.        , 0.27037983, ..., 0.        , 0.        ,
        0.        ],
       ...,
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ],
       [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
        0.        ]])

In [119]:
# Creating the Bag of Words model
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer(max_features = 1500)
X = cv.fit_transform(corpus).toarray()

In [120]:
X

array([[0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 1, 0],
       [0, 0, 1, ..., 0, 0, 0],
       ...,
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0],
       [0, 0, 0, ..., 0, 0, 0]], dtype=int64)

In [166]:
para='''good boy, good girl, good boy girl'''

In [167]:
sentences = nltk.sent_tokenize(para)

In [171]:
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(sentences)

In [172]:
sentences

['good boy, good girl, good boy girl']

In [181]:
len(sentences)

4

In [173]:
X

<1x3 sparse matrix of type '<class 'numpy.int64'>'
	with 3 stored elements in Compressed Sparse Row format>

In [174]:
from sklearn.feature_extraction.text import TfidfVectorizer
obj = TfidfVectorizer()
corpus = ['good boy, good girl, good boy girl']
X = obj.fit_transform(corpus).toarray()

In [175]:
X

array([[0.48507125, 0.48507125, 0.72760688]])

data cleaning tweet data

1)escaping HTML paser

In [134]:
original_tweet = "I luv my &lt;3 iphone &amp; you’re awsm apple. DisplayIsAwesome, sooo happppppy 🙂 http://www.apple.com"



In [135]:
tweet = original_tweet.decode("utf8").encode(‘ascii’,’ignore’)

SyntaxError: invalid character '‘' (U+2018) (Temp/ipykernel_8544/2879355225.py, line 1)

In [156]:
from sklearn.feature_extraction.text import TfidfVectorizer
obj = TfidfVectorizer()
corpus = ['This is sample document.', 'another random document.', 'third sample document text']
X = obj.fit_transform(corpus).toarray()

In [155]:
corpus

['This is sample document.',
 'another random document.',
 'third sample document text']

In [157]:
print(X)

[[0.         0.34520502 0.5844829  0.         0.44451431 0.
  0.         0.5844829 ]
 [0.65249088 0.38537163 0.         0.65249088 0.         0.
  0.         0.        ]
 [0.         0.34520502 0.         0.         0.44451431 0.5844829
  0.5844829  0.        ]]


In [260]:
from gensim.test.utils import common_texts
from gensim.models import Word2Vec
sentences = [['data', 'science'], ['vidhya', 'science', 'data', 'analytics'],['machine', 'learning'], ['deep', 'learning']]

In [261]:
# train the model on your corpus  
model = Word2Vec(sentences, min_count = 1)

In [263]:
words = model.wv.key_to_index 

In [264]:
words

{'learning': 0,
 'science': 1,
 'data': 2,
 'deep': 3,
 'machine': 4,
 'analytics': 5,
 'vidhya': 6}

In [267]:
model.wv.key_to_index['deep']

3

In [256]:
vector=model.wv['analytics']

In [257]:
vector

array([-8.7274825e-03,  2.1301615e-03, -8.7354420e-04, -9.3190884e-03,
       -9.4281426e-03, -1.4107180e-03,  4.4324086e-03,  3.7040710e-03,
       -6.4986930e-03, -6.8730675e-03, -4.9994122e-03, -2.2868442e-03,
       -7.2502876e-03, -9.6033178e-03, -2.7436293e-03, -8.3628409e-03,
       -6.0388758e-03, -5.6709289e-03, -2.3441375e-03, -1.7069972e-03,
       -8.9569986e-03, -7.3519943e-04,  8.1525063e-03,  7.6904297e-03,
       -7.2061159e-03, -3.6668312e-03,  3.1185520e-03, -9.5707225e-03,
        1.4764392e-03,  6.5244664e-03,  5.7464195e-03, -8.7630618e-03,
       -4.5171441e-03, -8.1401607e-03,  4.5956374e-05,  9.2636338e-03,
        5.9733056e-03,  5.0673080e-03,  5.0610625e-03, -3.2429171e-03,
        9.5521836e-03, -7.3564244e-03, -7.2703874e-03, -2.2653891e-03,
       -7.7856064e-04, -3.2161034e-03, -5.9258583e-04,  7.4888230e-03,
       -6.9751858e-04, -1.6249407e-03,  2.7443992e-03, -8.3591007e-03,
        7.8558037e-03,  8.5361041e-03, -9.5840869e-03,  2.4462664e-03,
      

In [246]:
words = list(model.wv.key_to_index)

In [247]:
print(words)

['learning', 'science', 'data', 'deep', 'machine', 'analytics', 'vidhya']


In [243]:
model.wv.key_to_index["data"]

2

In [244]:
model.wv.get_vecattr("machine", "count")

1

In [245]:
model.wv.most_similar(['data', 'science'])

[('machine', 0.1250143051147461),
 ('analytics', 0.05258499085903168),
 ('deep', 0.03897379711270332),
 ('vidhya', 0.02278798446059227),
 ('learning', -0.04521758854389191)]

In [207]:
model.wv.most_similar('science')

[('deep', 0.06797593832015991),
 ('analytics', 0.0093911774456501),
 ('machine', 0.0045030200853943825),
 ('learning', -0.010839177295565605),
 ('data', -0.023671656847000122),
 ('vidhya', -0.11410721391439438)]

In [ ]:
from gensim.test.utils import common_texts
from gensim.models import Word2Vec

In [235]:
# train the model on your corpus  
model = Word2Vec(corpus, min_count = 2)

In [233]:
corpus

['three visions india',
 'years history people world come invade us capture land conquer mind',
 'alexander onwards greeks turks moguls portuguese british french dutch come loot us take',
 'yet do nation',
 'conquer anyone',
 'grab land culture history try enforce way life',
 '',
 'respect freedom others first vision freedom',
 'believe india get first vision start war independence',
 'freedom must protect nurture build',
 'free one respect us',
 'second vision india development',
 'fifty years develop nation',
 'time see develop nation',
 'among top nations world term gdp',
 'percent growth rate areas',
 'poverty level fall',
 'achievements globally recognise today',
 'yet lack self confidence see develop nation self reliant self assure',
 'incorrect',
 'third vision',
 'india must stand world',
 'believe unless india stand world one respect us',
 'strength respect strength',
 'must strong military power also economic power',
 'must go hand hand',
 'good fortune work three great mind'

In [234]:
len(corpus)

31

In [258]:
model.wv.most_similar('work ')

KeyError: "Key 'work ' not present"

In [238]:
model.wv.key_to_index["india"]

KeyError: 'india'